name: shared_expenses_app
description: Simplify Group Expense Tracking
# version: 1.0.0
#homepage: https://www.sharedexpenses.app
#author: KRIS <kskotheim@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0

